sudo: false
os:
  - linux
  - osx
osx_image: xcode7.2
addons:
  apt:
    # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
before_script:
  - ./dev/bots/setup.sh
script:
  - ./dev/bots/test.sh
cache:
  directories:
    - $HOME/.pub-cache
